<?php
	ini_set('display_errors', '1');
	error_reporting(E_ALL);
	use DigitalSplash\Notification\Helpers\Notification;
	use DigitalSplash\Notification\Models\Template;

	include_once __DIR__ . '/../../../../../vendor/autoload.php';

	$case = 2;
	switch ($case) {
		//Case 1: Use Template with full functionality...
		case 1:
			$template = new Template(
				[
					'full_name' => 'Hadi Darwish',
					'button_text' => 'Test button',
					'url' => 'https://google.com'
				],
				true,
				'TestEmail'
			);
			$body = $template->getContent();
			break;

		//Case 2: Use Template main file only...
		case 2:
			$template = new Template(
				[
					'full_name' => 'Hadi Darwish',
					'button_text' => 'Test button',
					'url' => 'https://google.com'
				],
				true
			);
			$template->setMainTemplateContent('This Email content is generated by the user.');
			$body = $template->getContent();
			break;

		default:
			$body = 'This Email is fully generated by the user.';
	}
	echo $body;
	exit;

	$notification = new Notification();

	$notification->setSendEmail(true);

	$notification->model->appendTo('Testing Email', 'hadidarwish999@gmail.com');
	$notification->model->appendTo('Hadi Darwish', 'hadidarwish222@gmail.com');
	$notification->model->appendCC('Hadi','hadidarwish999@gmail.com');
	$notification->model->appendBCC('Hadi Darwish','hadidarwish222@gmail.com');
	$notification->model->appendToAttachment(__DIR__ . "/../../../../_CommonFiles/Media/users/profile/user-01.jpg", 'user-01.jpg');
	$notification->model->appendToAttachment(__DIR__ . "/../../../../_CommonFiles/Media/users/profile/user-01-th.jpg", 'user-01-th.jpg');
	$notification->model->appendToAttachment(__DIR__ . "/../../../../_CommonFiles/Media/users/profile/user-01.webp", 'user-01.webp');
	$notification->model->setSubject('Testing Email');
	$notification->model->email->setBody($body);

	$notificationResponse = $notification->send();
	var_dump($notificationResponse);
